baseURL: http://tobiaswillmann.com
languageCode: en-us
title: Photography
theme: b_ring

params:
  fullname: Tobias Willmann
  contact:
    mail: mail@tobiaswillmann.com
    instagram: https://www.instagram.com/tobias_willmann
  seo:
    description: Tobias Willmann's Portfolio
    keywords: art, photography, berlin
  show_slider_buttons: false
  show_pagination: false
